import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import type { Plugin } from "vite";
// vitest/config re-exports defineConfig with the `test` field merged into
// Vite's UserConfig type, so this one file works for `vite build`/`vite
// dev` and `vitest run` alike -- no separate vitest.config.ts needed.
import { defineConfig } from "vitest/config";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// design/tokens.css (one level up, outside frontend/) is generated by
// design/build_palettes.py and is the single source of colour truth for
// the whole app -- this SPA keys off it. Vite's dev
// server refuses to serve/import files outside its project root in some
// configurations, and a plain cross-directory `@import` risks silently
// going stale if someone forgets it exists. So instead: copy it into
// src/styles/tokens.generated.css on every dev-server start and every
// build (buildStart runs in both modes), stamp a header so nobody edits
// the copy directly, and watch the source file in dev so palette edits
// hot-reload. To change the palette: edit design/build_palettes.py's
// CHOSEN palette and rerun it, then just `npm run dev`/`npm run build`
// again -- this file is regenerated automatically, never committed.
const TOKENS_SRC = path.resolve(__dirname, "../design/tokens.css");
const TOKENS_DEST = path.resolve(__dirname, "src/styles/tokens.generated.css");

function syncDesignTokens(): Plugin {
  const write = () => {
    const source = fs.readFileSync(TOKENS_SRC, "utf-8");
    const header =
      "/* AUTO-COPIED from design/tokens.css by frontend/vite.config.ts (syncDesignTokens plugin).\n" +
      "   Do not edit this file by hand -- edit design/build_palettes.py and rerun it, then\n" +
      "   rerun `npm run dev` / `npm run build` to refresh this copy. */\n\n";
    fs.mkdirSync(path.dirname(TOKENS_DEST), { recursive: true });
    fs.writeFileSync(TOKENS_DEST, header + source);
  };

  return {
    name: "sync-design-tokens",
    buildStart() {
      write();
    },
    configureServer(server) {
      write();
      server.watcher.add(TOKENS_SRC);
      server.watcher.on("change", (file) => {
        if (path.resolve(file) === TOKENS_SRC) write();
      });
    },
  };
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [syncDesignTokens(), react(), tailwindcss()],
  server: {
    // Lets the dev server read design/tokens.css (outside frontend/) if
    // anything ever imports it directly; the plugin above copies it in
    // rather than relying on this, but it's a harmless safety net.
    fs: { allow: [".."] },
    // Dev-only convenience (spec C5: not required at runtime, the build
    // is what FastAPI actually serves) -- lets pages call fetch("/api/...")
    // the same way whether running under `npm run dev` or the built app,
    // instead of needing a base-URL switch. Points at app.py's fixed port.
    proxy: {
      "/api": "http://127.0.0.1:8765",
    },
  },
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
  },
});
