"""phase1 initial schema

Revision ID: 21b63e9bb1c0
Revises: 
Create Date: 2026-08-31 15:20:07.933059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21b63e9bb1c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_code'), ['code'], unique=True)

    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='planstatus'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_topic_id'), ['topic_id'], unique=False)

    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('lc_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('default_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'lc_id')
    )
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problem_topic_id'), ['topic_id'], unique=False)

    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pitfalls', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_signal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'code')
    )
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_topic_id'), ['topic_id'], unique=False)

    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('attempt_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.Enum('new', 'review', name='attemptkind'), nullable=False),
    sa.Column('review_task_id', sa.Integer(), nullable=True),
    sa.Column('duration_bucket', sa.Enum('within', 'over', 'unsolved', name='durationbucket'), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('time_limit_sec', sa.Integer(), nullable=False),
    sa.Column('submit_count', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Enum('A', 'B', 'C', name='mark'), nullable=False),
    sa.Column('used_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_attempt_date'), ['attempt_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_problem_id'), ['problem_id'], unique=False)

    op.create_table('planday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'skipped', 'postponed', name='daystatus'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'day_index')
    )
    with op.batch_alter_table('planday', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planday_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planday_planned_date'), ['planned_date'], unique=False)

    op.create_table('planitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_day_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'deferred', name='itemstatus'), nullable=False),
    sa.ForeignKeyConstraint(['plan_day_id'], ['planday.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_day_id', 'problem_id')
    )
    with op.batch_alter_table('planitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planitem_plan_day_id'), ['plan_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planitem_problem_id'), ['problem_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planitem_problem_id'))
        batch_op.drop_index(batch_op.f('ix_planitem_plan_day_id'))

    op.drop_table('planitem')
    with op.batch_alter_table('planday', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planday_planned_date'))
        batch_op.drop_index(batch_op.f('ix_planday_plan_id'))

    op.drop_table('planday')
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_problem_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_attempt_date'))

    op.drop_table('attempt')
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_topic_id'))

    op.drop_table('template')
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_topic_id'))

    op.drop_table('problem')
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_topic_id'))

    op.drop_table('plan')
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_code'))

    op.drop_table('topic')
    # ### end Alembic commands ###
